packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@firebase/util': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  protobufjs: false
  react-native-nitro-modules: true
  sharp: true
  unrs-resolver: true
