import type { Submission, Theme, Hotspot, Ranking, Insight } from "../types";

export const mockSubmissions: Submission[] = [
  {
    id: "1",
    title: "Upgrade Govt Primary School Building",
    description:
      "Classrooms need urgent repair, roof leaks during monsoon, no separate toilets for girls. Enrollment dropping.",
    source: "public_meeting",
    region: "North Constituency",
    category: "education",
    sentiment: "negative",
    submittedAt: "2025-06-15",
    language: "English",
    upvotes: 142,
    status: "under_review",
  },
  {
    id: "2",
    title: "New Vocational Training Centre",
    description:
      "Youth need skill training for IT, tailoring, and electrical work. Proposed centre on govt land near bus stand.",
    source: "direct_representation",
    region: "East Constituency",
    category: "education",
    sentiment: "positive",
    submittedAt: "2025-06-18",
    language: "Hindi",
    upvotes: 89,
    status: "pending",
  },
  {
    id: "3",
    title: "Bridge Repair on NH-48 Connecting Village",
    description:
      "Bridge damaged in last rains. School children and elderly risk daily. Need immediate repair or new bridge.",
    source: "grievance_portal",
    region: "West Constituency",
    category: "infrastructure",
    sentiment: "negative",
    submittedAt: "2025-06-20",
    language: "English",
    upvotes: 210,
    status: "approved",
  },
  {
    id: "4",
    title: "Mobile Health Clinic for Tribal Hamlet",
    description: "No PHC within 12km. Malaria and waterborne diseases rising. Monthly mobile clinic requested.",
    source: "public_meeting",
    region: "South Constituency",
    category: "healthcare",
    sentiment: "negative",
    submittedAt: "2025-06-22",
    language: "English",
    upvotes: 167,
    status: "under_review",
  },
  {
    id: "5",
    title: "Rainwater Harvesting in Govt Schools",
    description: "Groundwater depleting fast. Schools have large rooftops — install rooftop RWH systems.",
    source: "social_media",
    region: "North Constituency",
    category: "environment",
    sentiment: "positive",
    submittedAt: "2025-06-25",
    language: "English",
    upvotes: 76,
    status: "pending",
  },
  {
    id: "6",
    title: "Anganwadi Centre Upgradation",
    description: "Current centre is a single room. Need kitchen, sleeping area, and play space for 45 children.",
    source: "letter",
    region: "East Constituency",
    category: "education",
    sentiment: "neutral",
    submittedAt: "2025-06-28",
    language: "Hindi",
    upvotes: 54,
    status: "pending",
  },
  {
    id: "7",
    title: "Street Lights on Main Market Road",
    description: "Entire stretch dark after 7pm. Women and shopkeepers feel unsafe. Request for LED street lights.",
    source: "grievance_portal",
    region: "South Constituency",
    category: "infrastructure",
    sentiment: "negative",
    submittedAt: "2025-07-01",
    language: "English",
    upvotes: 98,
    status: "approved",
  },
  {
    id: "8",
    title: "Skill Development for Women SHGs",
    description: "200+ women in self-help groups need training in digital literacy and small business management.",
    source: "direct_representation",
    region: "West Constituency",
    category: "employment",
    sentiment: "positive",
    submittedAt: "2025-07-03",
    language: "English",
    upvotes: 132,
    status: "in_progress",
  },
];

export const mockThemes: Theme[] = [
  {
    id: "t1",
    name: "School Infrastructure & Education",
    category: "education",
    frequency: 34,
    regions: ["North Constituency", "East Constituency", "South Constituency"],
    avgSentiment: -0.4,
    trend: "up",
  },
  {
    id: "t2",
    name: "Healthcare Accessibility",
    category: "healthcare",
    frequency: 28,
    regions: ["South Constituency", "West Constituency"],
    avgSentiment: -0.6,
    trend: "up",
  },
  {
    id: "t3",
    name: "Roads & Bridge Connectivity",
    category: "infrastructure",
    frequency: 22,
    regions: ["West Constituency", "North Constituency"],
    avgSentiment: -0.5,
    trend: "up",
  },
  {
    id: "t4",
    name: "Employment & Skill Development",
    category: "employment",
    frequency: 19,
    regions: ["East Constituency", "West Constituency"],
    avgSentiment: 0.2,
    trend: "stable",
  },
  {
    id: "t5",
    name: "Water Conservation & Environment",
    category: "environment",
    frequency: 15,
    regions: ["North Constituency", "South Constituency"],
    avgSentiment: 0.3,
    trend: "up",
  },
];

export const mockHotspots: Hotspot[] = [
  {
    id: "h1",
    region: "South Constituency",
    demandScore: 92,
    topIssue: "Healthcare Accessibility",
    submissionCount: 28,
    growthRate: 12.5,
    latitude: 12.9716,
    longitude: 77.5946,
  },
  {
    id: "h2",
    region: "North Constituency",
    demandScore: 85,
    topIssue: "School Infrastructure",
    submissionCount: 34,
    growthRate: 8.3,
    latitude: 13.0827,
    longitude: 80.2707,
  },
  {
    id: "h3",
    region: "West Constituency",
    demandScore: 78,
    topIssue: "Roads & Bridge Connectivity",
    submissionCount: 22,
    growthRate: -2.1,
    latitude: 19.076,
    longitude: 72.8777,
  },
  {
    id: "h4",
    region: "East Constituency",
    demandScore: 65,
    topIssue: "Employment & Skill Development",
    submissionCount: 19,
    growthRate: 4.7,
    latitude: 22.5726,
    longitude: 88.3639,
  },
];

export const mockRankings: Ranking[] = [
  {
    id: "r1",
    project: "Govt Primary School Upgradation — North",
    category: "education",
    region: "North Constituency",
    demandScore: 94,
    alignmentScore: 88,
    infrastructureGap: 92,
    priorityScore: 91.3,
    status: "proposed",
    budgetEstimate: 4500000,
    beneficiaries: 1200,
  },
  {
    id: "r2",
    project: "Mobile Health Clinic — South",
    category: "healthcare",
    region: "South Constituency",
    demandScore: 91,
    alignmentScore: 85,
    infrastructureGap: 96,
    priorityScore: 90.7,
    status: "proposed",
    budgetEstimate: 2800000,
    beneficiaries: 8500,
  },
  {
    id: "r3",
    project: "Bridge Repair NH-48 — West",
    category: "infrastructure",
    region: "West Constituency",
    demandScore: 88,
    alignmentScore: 90,
    infrastructureGap: 72,
    priorityScore: 83.3,
    status: "approved",
    budgetEstimate: 12000000,
    beneficiaries: 25000,
  },
  {
    id: "r4",
    project: "Vocational Training Centre — East",
    category: "education",
    region: "East Constituency",
    demandScore: 76,
    alignmentScore: 82,
    infrastructureGap: 68,
    priorityScore: 75.3,
    status: "proposed",
    budgetEstimate: 3500000,
    beneficiaries: 600,
  },
  {
    id: "r5",
    project: "Women SHG Skill Development — West",
    category: "employment",
    region: "West Constituency",
    demandScore: 71,
    alignmentScore: 79,
    infrastructureGap: 45,
    priorityScore: 65.0,
    status: "in_progress",
    budgetEstimate: 1200000,
    beneficiaries: 200,
  },
];

export const mockInsights: Insight[] = [
  {
    id: "i1",
    type: "correlation",
    title: "School complaints peak with enrollment decline",
    description:
      "Submissions about school infrastructure show 78% correlation with falling enrollment in North Constituency zones.",
    confidence: 0.89,
    relatedProjects: ["r1"],
  },
  {
    id: "i2",
    type: "anomaly",
    title: "Healthcare gap is 3x higher than projected",
    description:
      "Actual demand in South Constituency exceeds model predictions by 300%. Likely due to recent clinic closure.",
    confidence: 0.94,
    relatedProjects: ["r2"],
  },
  {
    id: "i3",
    type: "prediction",
    title: "Bridge repair demand will saturate by Q3",
    description:
      "Current submission velocity for bridge issues suggests the gap will self-resolve within 90 days if delayed.",
    confidence: 0.72,
    relatedProjects: ["r3"],
  },
  {
    id: "i4",
    type: "recommendation",
    title: "Merge vocational centre with existing polytechnic",
    description:
      "Cost saving of 40% predicted by utilizing existing infrastructure rather than constructing new facility.",
    confidence: 0.81,
    relatedProjects: ["r4", "r5"],
  },
];

export const categoryColors: Record<string, string> = {
  education: "#3b82f6",
  healthcare: "#10b981",
  infrastructure: "#f59e0b",
  employment: "#8b5cf6",
  environment: "#06b6d4",
};

export const sentimentColors: Record<string, string> = {
  positive: "#10b981",
  neutral: "#64748b",
  negative: "#ef4444",
};

export const statusColors: Record<string, string> = {
  proposed: "#94a3b8",
  approved: "#3b82f6",
  in_progress: "#f59e0b",
  completed: "#10b981",
  pending: "#cbd5e1",
  under_review: "#f59e0b",
  rejected: "#ef4444",
};
